# name of the software
name: Photo Sphere Viewer
# current version of the software
version: 3.2.2
# licence of the software
license: MIT License
licenseUrl: http://opensource.org/licenses/MIT

# download button
download:
  popup: true
  url: https://github.com/mistic100/Photo-Sphere-Viewer/archive/3.2.2.zip
  bower: Photo-Sphere-Viewer
  npm: photo-sphere-viewer
  cdn:
    url:
    img:
    name:

favicon: png

# list of additional links on the right of the top menu
headerLinks:
  - title: GitHub
    url: https://github.com/mistic100/Photo-Sphere-Viewer
  - title: StrangePlanet
    url: http://www.strangeplanet.fr
  - title: Jérémy Heleine
    url: http://jeremyheleine.me

# list if additional links on the footer
footerLinks:
  - title: GitHub
    url: https://github.com/mistic100/Photo-Sphere-Viewer
  - title: Issues
    url: https://github.com/mistic100/Photo-Sphere-Viewer/issues?state=open

# header
header:
  color1: "#09B4E9"
  color2: "#15884C"
  trianglify: true

# google analytics
analytics:
  account: UA-28192323-3
  domain: auto

# github buttons
githubButton:
  user: mistic100
  repo: Photo-Sphere-Viewer

# twitter buttons
twitter:
  enabled: true
  via: mistic100
  hash: PhotoSphere
  account: mistic100

# facebook buttons
facebook:
  enabled: true
  profileUrl:


exclude: ['README.md', 'LICENSE', 'bower.json', 'Gemfile.lock', 'Gemfile']
